<a href="https://colab.research.google.com/github/sohag221/Deep-Learning/blob/main/churn_predict_with_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
# prompt: load tensorflow and keras.

!pip install tensorflow
import tensorflow as tf
from tensorflow import keras
print(tf.__version__)
keras.__version__


2.18.0


'3.8.0'

In [6]:
import pandas as pd
import numpy as np
import plotly.express as px
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler , LabelEncoder , OneHotEncoder
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import load_model

In [13]:
data = pd.read_csv('/content/drive/MyDrive/Statistical dataset/Customer_churn_Prediction(Internet user).csv')
data.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [14]:
data.shape

(7043, 21)

In [16]:
data.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [17]:
data = data.drop(['customerID'] , axis = 1)

In [18]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

for col in data.columns:
  if data[col].dtype == 'object':
    data[col] = le.fit_transform(data[col])

In [19]:
data

gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0          0              0        1           0       1             0   
1          1              0        0           0      34             1   
2          1              0        0           0       2             1   
3          1              0        0           0      45             0   
4          0              0        0           0       2             1   
...      ...            ...      ...         ...     ...           ...   
7038       1              0        1           1      24             1   
7039       0              0        1           1      72             1   
7040       0              0        1           1      11             0   
7041       1              1        1           0       4             1   
7042       1              0        0           0      66             1   

      MultipleLines  InternetService  OnlineSecurity  OnlineBackup  \
0                 1                0               0             2   
1                 0                0               2             0   
2                 0                0               2             2   
3                 1                0               2             0   
4                 0                1               0             0   
...             ...              ...             ...           ...   
7038              2                0               2             0   
7039              2                1               0             2   
7040              1                0               2             0   
7041              2                1               0             0   
7042              0                1               2             0   

      DeviceProtection  TechSupport  StreamingTV  StreamingMovies  Contract  \
0                    0            0            0                0         0   
1                    2            0            0                0         1   
2                    0            0            0                0         0   
3                    2            2            0                0         1   
4                    0            0            0                0         0   
...                ...          ...          ...              ...       ...   
7038                 2            2            2                2         1   
7039                 2            0            2                2         1   
7040                 0            0            0                0         0   
7041                 0            0            0                0         0   
7042                 2            2            2                2         2   

      PaperlessBilling  PaymentMethod  MonthlyCharges  TotalCharges  Churn  
0                    1              2           29.85          2505      0  
1                    0              3           56.95          1466      0  
2                    1              3           53.85           157      1  
3                    0              0           42.30          1400      0  
4                    1              2           70.70           925      1  
...                ...            ...             ...           ...    ...  
7038                 1              3           84.80          1597      0  
7039                 1              1          103.20          5698      0  
7040                 1              2           29.60          2994      0  
7041                 1              3           74.40          2660      1  
7042                 1              0          105.65          5407      0  

[7043 rows x 20 columns]

In [20]:
X = data.drop(['Churn'] , axis = 1)
y = data['Churn']


In [22]:
scalar = StandardScaler()
X=scalar.fit_transform(X)

In [23]:
data.corr()

gender  SeniorCitizen   Partner  Dependents    tenure  \
gender            1.000000      -0.001492 -0.001808    0.010517  0.005095   
SeniorCitizen    -0.001492       1.000000  0.016101   -0.211362  0.016090   
Partner          -0.001808       0.016101  1.000000    0.452676  0.379689   
Dependents        0.010517      -0.211362  0.452676    1.000000  0.159722   
tenure            0.005095       0.016090  0.379689    0.159722  1.000000   
PhoneService     -0.006488       0.008699  0.017706   -0.001762  0.008445   
MultipleLines    -0.006739       0.145751  0.142410   -0.024991  0.343022   
InternetService  -0.000863      -0.032754  0.000891    0.044590 -0.030361   
OnlineSecurity   -0.015017      -0.128530  0.150828    0.152166  0.325455   
OnlineBackup     -0.012057      -0.014024  0.153130    0.091015  0.370866   
DeviceProtection  0.000549      -0.021786  0.166330    0.080537  0.371121   
TechSupport      -0.006825      -0.151571  0.126733    0.133524  0.322956   
StreamingTV      -0.006103       0.030195  0.137031    0.046675  0.289004   
StreamingMovies  -0.008743       0.046818  0.129574    0.021321  0.296882   
Contract          0.000126      -0.142823  0.294806    0.243187  0.671623   
PaperlessBilling -0.011754       0.156794 -0.014877   -0.111377  0.006143   
PaymentMethod     0.017352      -0.038744 -0.154798   -0.040292 -0.370444   
MonthlyCharges   -0.014569       0.219856  0.096848   -0.113890  0.247890   
TotalCharges     -0.005291       0.038234  0.059568   -0.009572  0.158518   
Churn            -0.008612       0.151477 -0.150448   -0.164221 -0.352251   

                  PhoneService  MultipleLines  InternetService  \
gender               -0.006488      -0.006739        -0.000863   
SeniorCitizen         0.008699       0.145751        -0.032754   
Partner               0.017706       0.142410         0.000891   
Dependents           -0.001762      -0.024991         0.044590   
tenure                0.008445       0.343022        -0.030361   
PhoneService          1.000000      -0.020538         0.387436   
MultipleLines        -0.020538       1.000000        -0.109216   
InternetService       0.387436      -0.109216         1.000000   
OnlineSecurity       -0.015198       0.007141        -0.028416   
OnlineBackup          0.024105       0.117327         0.036138   
DeviceProtection      0.003727       0.122318         0.044944   
TechSupport          -0.019158       0.011466        -0.026047   
StreamingTV           0.055458       0.174740         0.107471   
StreamingMovies       0.043870       0.180957         0.098350   
Contract              0.002247       0.110842         0.099721   
PaperlessBilling      0.016505       0.165146        -0.138625   
PaymentMethod        -0.004184      -0.176793         0.086140   
MonthlyCharges        0.247398       0.433576        -0.323260   
TotalCharges          0.083195       0.114955        -0.055724   
Churn                 0.011942       0.038037        -0.047291   

                  OnlineSecurity  OnlineBackup  DeviceProtection  TechSupport  \
gender                 -0.015017     -0.012057          0.000549    -0.006825   
SeniorCitizen          -0.128530     -0.014024         -0.021786    -0.151571   
Partner                 0.150828      0.153130          0.166330     0.126733   
Dependents              0.152166      0.091015          0.080537     0.133524   
tenure                  0.325455      0.370866          0.371121     0.322956   
PhoneService           -0.015198      0.024105          0.003727    -0.019158   
MultipleLines           0.007141      0.117327          0.122318     0.011466   
InternetService        -0.028416      0.036138          0.044944    -0.026047   
OnlineSecurity          1.000000      0.185126          0.175985     0.285028   
OnlineBackup            0.185126      1.000000          0.187757     0.195748   
DeviceProtection        0.175985      0.187757          1.000000     0.240593   
TechSupport             0.285028      0.195

In [24]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42,stratify=y)

In [25]:
x_train.shape

(4930, 19)

In [27]:
x_train[0]

array([-1.00955867, -0.44014635, -0.96662231, -0.65401193, -1.11456292,
        0.32743831, -0.9915883 ,  0.17225018, -0.91883775, -1.02991925,
       -1.02791014, -0.92526212,  1.14622038, -1.12140513, -0.8282069 ,
       -1.20511329,  0.39855772,  0.51310666,  0.01493513])

**Model Creat**

In [29]:
model = Sequential([
    Dense (units=32, activation='relu', input_dim=len(x_train[1])),
    Dense (units=64, activation='relu'),
    Dense (units=32, activation='relu'),
    Dense (units=1, activation='sigmoid')]
)

In [30]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [32]:
history = model.fit(
    x_train, y_train,
    validation_data=(x_test, y_test),
    epochs=10,
    batch_size=100
)

Epoch 1/10
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8100 - loss: 0.4126 - val_accuracy: 0.7889 - val_loss: 0.4341
Epoch 2/10
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8163 - loss: 0.4010 - val_accuracy: 0.7795 - val_loss: 0.4364
Epoch 3/10
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8116 - loss: 0.4031 - val_accuracy: 0.7922 - val_loss: 0.4333
Epoch 4/10
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8299 - loss: 0.3804 - val_accuracy: 0.7842 - val_loss: 0.4346
Epoch 5/10
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8254 - loss: 0.3939 - val_accuracy: 0.7875 - val_loss: 0.4366
Epoch 6/10
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8190 - loss: 0.4002 - val_accuracy: 0.7856 - val_loss: 0.4371
Epoch 7/10
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8263 - loss: 0.3745 - val_accuracy: 0.7847 - val_loss: 0.4403
Epoch 8/10
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8059 - loss: 0.3987 - val_accuracy: 0.7866 - val_loss:

In [33]:
model.evaluate(x_test,y_test)

67/67 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7783 - loss: 0.4493


[0.4408949613571167, 0.7832465767860413]

In [36]:
y_pred = model.predict(x_test)
y_pred = y_pred > 0.5

67/67 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


In [38]:
y_pred

array([[ True],
       [False],
       [ True],
       ...,
       [False],
       [ True],
       [False]])

In [37]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.84      0.87      0.86      1552
           1       0.60      0.54      0.57       561

    accuracy                           0.78      2113
   macro avg       0.72      0.71      0.71      2113
weighted avg       0.78      0.78      0.78      2113



In [39]:
confusion_matrix(y_test,y_pred)

array([[1351,  201],
       [ 257,  304]])